// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    $(".owl-carousel").owlCarousel({
      items: 4,
      margin: 100,
      navigation: true,
      dots: true,
      autoWidth: true
    });
    return $('.owl-carousel__testimonials').owlCarousel({
      navigation: true,
      singleItem: true
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
